<?php

namespace Database\Seeders;

use App\Enums\ActiveEnum;
use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Country::truncate();
        $data = [
            ["code" => 'AF', "name" => 'Afghanistan', "phone_code" => '93', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AL', "name" => 'Albania', "phone_code" => '355', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'DZ', "name" => 'Algeria', "phone_code" => '213', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AS', "name" => 'American Samoa', "phone_code" => '684', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AD', "name" => 'Andorra', "phone_code" => '376', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AO', "name" => 'Angola', "phone_code" => '244', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AI', "name" => 'Anguilla', "phone_code" => '264', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AQ', "name" => 'Antarctica', "phone_code" => '672', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AG', "name" => 'Antigua and Barbuda', "phone_code" => '268', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AR', "name" => 'Argentina', "phone_code" => '54', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AM', "name" => 'Armenia', "phone_code" => '374', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AW', "name" => 'Aruba', "phone_code" => '297', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AU', "name" => 'Australia', "phone_code" => '61', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AT', "name" => 'Austria', "phone_code" => '43', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AZ', "name" => 'Azerbaijan', "phone_code" => '994', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BS', "name" => 'Bahamas', "phone_code" => '242', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BH', "name" => 'Bahrain', "phone_code" => '973', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BD', "name" => 'Bangladesh', "phone_code" => '880', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BB', "name" => 'Barbados', "phone_code" => '246', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BY', "name" => 'Belarus', "phone_code" => '375', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BE', "name" => 'Belgium', "phone_code" => '32', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BZ', "name" => 'Belize', "phone_code" => '501', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BJ', "name" => 'Benin', "phone_code" => '229', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BM', "name" => 'Bermuda', "phone_code" => '441', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BT', "name" => 'Bhutan', "phone_code" => '975', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BO', "name" => 'Bolivia', "phone_code" => '591', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BA', "name" => 'Bosnia and Herzegovina', "phone_code" => '387', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BW', "name" => 'Botswana', "phone_code" => '267', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BR', "name" => 'Brazil', "phone_code" => '55', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'VG', "name" => 'British Virgin Islands', "phone_code" => '284', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BN', "name" => 'Brunei', "phone_code" => '673', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BG', "name" => 'Bulgaria', "phone_code" => '359', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BF', "name" => 'Burkina Faso', "phone_code" => '226', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'BI', "name" => 'Burundi', "phone_code" => '257', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KH', "name" => 'Cambodia', "phone_code" => '855', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CM', "name" => 'Cameroon', "phone_code" => '237', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CA', "name" => 'Canada', "phone_code" => '1', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CV', "name" => 'Cape Verde', "phone_code" => '238', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KY', "name" => 'Cayman Islands', "phone_code" => '345', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CF', "name" => 'Central African Republic', "phone_code" => '236', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TD', "name" => 'Chad', "phone_code" => '235', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CL', "name" => 'Chile', "phone_code" => '56', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CN', "name" => 'China', "phone_code" => '86', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CX', "name" => 'Christmas Island', "phone_code" => '61', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CC', "name" => 'Cocos Keeling Islands', "phone_code" => '61', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CO', "name" => 'Colombia', "phone_code" => '57', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KM', "name" => 'Comoros', "phone_code" => '269', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CD', "name" => 'Congo DRC', "phone_code" => '242', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CG', "name" => 'Congo Republic', "phone_code" => '682', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CK', "name" => 'Cook Islands', "phone_code" => '506', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CR', "name" => 'Costa Rica', "phone_code" => '385', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'HR', "name" => 'Croatia', "phone_code" => '53', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CU', "name" => 'Cuba', "phone_code" => '599', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CY', "name" => 'Cyprus', "phone_code" => '357', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CZ', "name" => 'Czech Republic', "phone_code" => '420', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'DK', "name" => 'Denmark', "phone_code" => '45', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'DJ', "name" => 'Djibouti', "phone_code" => '253', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'DM', "name" => 'Dominica', "phone_code" => '767', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'DO', "name" => 'Dominican Republic', "phone_code" => '809', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TL', "name" => 'East Timor', "phone_code" => '56', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'EC', "name" => 'Ecuador', "phone_code" => '593', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'EG', "name" => 'Egypt', "phone_code" => '20', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SV', "name" => 'El Salvador', "phone_code" => '503', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GQ', "name" => 'Equatorial Guinea', "phone_code" => '240', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'ER', "name" => 'Eritrea', "phone_code" => '291', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'EE', "name" => 'Estonia', "phone_code" => '372', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'ET', "name" => 'Ethiopia', "phone_code" => '251', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'FK', "name" => 'Falkland Islands', "phone_code" => '500', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'FO', "name" => 'Faroe Islands', "phone_code" => '298', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'FJ', "name" => 'Fiji', "phone_code" => '679', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'FI', "name" => 'Finland', "phone_code" => '358', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'FR', "name" => 'France', "phone_code" => '33', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GF', "name" => 'French Guiana', "phone_code" => '596', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PF', "name" => 'French Polynesia', "phone_code" => '594', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TF', "name" => 'French Southern Territories', "phone_code" => '689', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GA', "name" => 'Gabon', "phone_code" => '241', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GM', "name" => 'Gambia', "phone_code" => '220', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GE', "name" => 'Georgia', "phone_code" => '995', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'DE', "name" => 'Germany', "phone_code" => '49', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GH', "name" => 'Ghana', "phone_code" => '233', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GI', "name" => 'Gibraltar', "phone_code" => '350', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GR', "name" => 'Greece', "phone_code" => '30', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GL', "name" => 'Greenland', "phone_code" => '299', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GD', "name" => 'Grenada', "phone_code" => '473', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GP', "name" => 'Guadeloupe', "phone_code" => '590', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GU', "name" => 'Guam', "phone_code" => '671', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GT', "name" => 'Guatemala', "phone_code" => '502', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GN', "name" => 'Guinea', "phone_code" => '594', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GW', "name" => 'Guinea-Bissau', "phone_code" => '245', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GY', "name" => 'Guyana', "phone_code" => '592', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'HT', "name" => 'Haiti', "phone_code" => '509', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'HN', "name" => 'Honduras', "phone_code" => '504', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'HK', "name" => 'Hong Kong', "phone_code" => '852', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'HU', "name" => 'Hungary', "phone_code" => '36', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'IS', "name" => 'Iceland', "phone_code" => '354', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'IN', "name" => 'India', "phone_code" => '91', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'ID', "name" => 'Indonesia', "phone_code" => '62', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'IR', "name" => 'Iran', "phone_code" => '98', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'IQ', "name" => 'Iraq', "phone_code" => '964', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'IE', "name" => 'Ireland', "phone_code" => '353', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'IM', "name" => 'Isle of Man', "phone_code" => '44', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'IL', "name" => 'Israel', "phone_code" => '972', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'IT', "name" => 'Italy', "phone_code" => '39', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CI', "name" => 'Ivory Coast', "phone_code" => '225', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'JM', "name" => 'Jamaica', "phone_code" => '876', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'JP', "name" => 'Japan', "phone_code" => '81', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'JO', "name" => 'Jordan', "phone_code" => '962', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KZ', "name" => 'Kazakhstan', "phone_code" => '7', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KE', "name" => 'Kenya', "phone_code" => '254', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KI', "name" => 'Kiribati', "phone_code" => '686', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'XK', "name" => 'Kosovo', "phone_code" => '381', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KW', "name" => 'Kuwait', "phone_code" => '965', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KG', "name" => 'Kyrgyzstan', "phone_code" => '996', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LA', "name" => 'Laos', "phone_code" => '856', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LV', "name" => 'Latvia', "phone_code" => '371', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LB', "name" => 'Lebanon', "phone_code" => '961', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LS', "name" => 'Lesotho', "phone_code" => '266', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LR', "name" => 'Liberia', "phone_code" => '231', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LY', "name" => 'Libya', "phone_code" => '218', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LI', "name" => 'Liechtenstein', "phone_code" => '423', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LT', "name" => 'Lithuania', "phone_code" => '370', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LU', "name" => 'Luxembourg', "phone_code" => '352', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MO', "name" => 'Macau', "phone_code" => '853', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MK', "name" => 'Macedonia', "phone_code" => '389', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MG', "name" => 'Madagascar', "phone_code" => '261', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MW', "name" => 'Malawi', "phone_code" => '265', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MY', "name" => 'Malaysia', "phone_code" => '60', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MV', "name" => 'Maldives', "phone_code" => '960', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'ML', "name" => 'Mali', "phone_code" => '223', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MT', "name" => 'Malta', "phone_code" => '356', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MH', "name" => 'Marshall Islands', "phone_code" => '692', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MQ', "name" => 'Martinique', "phone_code" => '670', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MR', "name" => 'Mauritania', "phone_code" => '222', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MU', "name" => 'Mauritius', "phone_code" => '230', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'YT', "name" => 'Mayotte', "phone_code" => '269', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MX', "name" => 'Mexico', "phone_code" => '52', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'FM', "name" => 'Micronesia', "phone_code" => '691', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MD', "name" => 'Moldova', "phone_code" => '373', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MC', "name" => 'Monaco', "phone_code" => '377', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MN', "name" => 'Mongolia', "phone_code" => '976', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MS', "name" => 'Montserrat', "phone_code" => '664', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MA', "name" => 'Morocco', "phone_code" => '212', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MZ', "name" => 'Mozambique', "phone_code" => '258', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'MM', "name" => 'Myanmar Burma', "phone_code" => '95', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NA', "name" => 'Namibia', "phone_code" => '264', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NR', "name" => 'Nauru', "phone_code" => '674', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NP', "name" => 'Nepal', "phone_code" => '977', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NL', "name" => 'Netherlands', "phone_code" => '31', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AN', "name" => 'Netherlands Antilles', "phone_code" => '599', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NC', "name" => 'New Caledonia', "phone_code" => '687', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NZ', "name" => 'New Zealand', "phone_code" => '64', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NI', "name" => 'Nicaragua', "phone_code" => '505', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NE', "name" => 'Niger', "phone_code" => '227', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NG', "name" => 'Nigeria', "phone_code" => '234', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NU', "name" => 'Niue', "phone_code" => '683', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NF', "name" => 'Norfolk Island', "phone_code" => '672', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KP', "name" => 'North Korea', "phone_code" => '850', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'NO', "name" => 'Norway', "phone_code" => '47', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'OM', "name" => 'Oman', "phone_code" => '968', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PK', "name" => 'Pakistan', "phone_code" => '92', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PW', "name" => 'Palau', "phone_code" => '680', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PA', "name" => 'Panama', "phone_code" => '507', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PG', "name" => 'Papua New Guinea', "phone_code" => '675', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PY', "name" => 'Paraguay', "phone_code" => '595', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PE', "name" => 'Peru', "phone_code" => '51', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PH', "name" => 'Philippines', "phone_code" => '63', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PN', "name" => 'Pitcairn Islands', "phone_code" => '48', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PL', "name" => 'Poland', "phone_code" => '351', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PT', "name" => 'Portugal', "phone_code" => '239', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PR', "name" => 'Puerto Rico', "phone_code" => '787', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'QA', "name" => 'Qatar', "phone_code" => '974', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'RE', "name" => 'R', "phone_code" => '262', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'RO', "name" => 'Romania', "phone_code" => '40', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'RU', "name" => 'Russia', "phone_code" => '7', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'RW', "name" => 'Rwanda', "phone_code" => '250', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SH', "name" => 'Saint Helena', "phone_code" => '290', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KN', "name" => 'Saint Kitts and Nevis', "phone_code" => '869', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LC', "name" => 'Saint Lucia', "phone_code" => '758', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'PM', "name" => 'Saint Pierre and Miquelon', "phone_code" => '508', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'VC', "name" => 'Saint Vincent and the Grenadines', "phone_code" => '784', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SM', "name" => 'San Marino', "phone_code" => '378', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'ST', "name" => 'Sao Tome and Principe', "phone_code" => '239', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SA', "name" => 'Saudi Arabia', "phone_code" => '966', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SN', "name" => 'Senegal', "phone_code" => '221', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'RS', "name" => 'Serbia', "phone_code" => '381', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SC', "name" => 'Seychelles', "phone_code" => '248', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SL', "name" => 'Sierra Leone', "phone_code" => '232', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SG', "name" => 'Singapore', "phone_code" => '65', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SK', "name" => 'Slovakia', "phone_code" => '421', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SI', "name" => 'Slovenia', "phone_code" => '386', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SB', "name" => 'Solomon Islands', "phone_code" => '677', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SO', "name" => 'Somalia', "phone_code" => '252', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'ZA', "name" => 'South Africa', "phone_code" => '27', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'KR', "name" => 'South Korea', "phone_code" => '82', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'ES', "name" => 'Spain', "phone_code" => '34', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'LK', "name" => 'Sri Lanka', "phone_code" => '94', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SD', "name" => 'Sudan', "phone_code" => '249', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SR', "name" => 'Suriname', "phone_code" => '597', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SZ', "name" => 'Swaziland', "phone_code" => '268', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SE', "name" => 'Sweden', "phone_code" => '46', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CH', "name" => 'Switzerland', "phone_code" => '41', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'SY', "name" => 'Syria', "phone_code" => '963', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TW', "name" => 'Taiwan', "phone_code" => '886', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TJ', "name" => 'Tajikistan', "phone_code" => '992', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TZ', "name" => 'Tanzania', "phone_code" => '255', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TH', "name" => 'Thailand', "phone_code" => '66', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TG', "name" => 'Togo', "phone_code" => '228', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TK', "name" => 'Tokelau', "phone_code" => '690', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TO', "name" => 'Tonga', "phone_code" => '676', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TT', "name" => 'Trinidad and Tobago', "phone_code" => '868', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TN', "name" => 'Tunisia', "phone_code" => '216', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TR', "name" => 'Turkey', "phone_code" => '90', "is_active" => ActiveEnum::ACTIVE->value],
            ["code" => 'TM', "name" => 'Turkmenistan', "phone_code" => '993', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TC', "name" => 'Turks and Caicos Islands', "phone_code" => '649', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'TV', "name" => 'Tuvalu', "phone_code" => '688', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'VI', "name" => 'U.S. Virgin Islands', "phone_code" => '340', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'UG', "name" => 'Uganda', "phone_code" => '256', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'UA', "name" => 'Ukraine', "phone_code" => '380', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'AE', "name" => 'United Arab Emirates', "phone_code" => '971', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'GB', "name" => 'United Kingdom', "phone_code" => '44', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'US', "name" => 'United States', "phone_code" => '1', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'UY', "name" => 'Uruguay', "phone_code" => '598', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'UZ', "name" => 'Uzbekistan', "phone_code" => '998', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'VU', "name" => 'Vanuatu', "phone_code" => '678', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'VA', "name" => 'Vatican City', "phone_code" => '39', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'VE', "name" => 'Venezuela', "phone_code" => '58', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'VN', "name" => 'Vietnam', "phone_code" => '84', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'WF', "name" => 'Wallis and Futuna', "phone_code" => '681', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'YE', "name" => 'Yemen', "phone_code" => '967', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'ZM', "name" => 'Zambia', "phone_code" => '260', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'ZW', "name" => 'Zimbabwe', "phone_code" => '263', "is_active" => ActiveEnum::PASSIVE->value],
            ["code" => 'CY', "name" => 'KKTC', "phone_code" => '90', "is_active" => ActiveEnum::PASSIVE->value]
        ];

        foreach ($data as $key => $country) {
            Country::create([
                "name" => $country['name'],
                "code" => $country['code'],
                "photo_link" => "https://flagcdn.com/160x120/" . strtolower($country['code']) . ".png",
                "phone_code" => "+" . $country['phone_code'],
                "phone_mask" => "(###) ###-####",
                'order_number' => $key,
                'is_active' => $country['is_active'],
            ]);
        }
    }
}
